### ISSUE TITLE
Unable to debug & D1 Mini GPIO

### ISSUE THREAD

**Issue by jeylites** [washcroft/HttpGarageDoorController#3]
Unable to see if device connected to the router or not, previously, I was able to see the messages after  uncommented '#define DEBUG 

Here is the changes I made...
#define LOG_LEVEL 3 // ERROR = 1, INFO = 2, DEBUG = 3, VERBOSE = 4, TRACE = 5

**Baud: 115200** 
ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v3de0c112
~ld

I'm currently using a Wemos D1 mini for this project, 
![esp12-f_pinout3](https://user-images.githubusercontent.com/9190080/31237035-6a1fd566-a9bb-11e7-9b5f-78d9b5d6e0fe.jpg)

Are the GPIO pin the same as the sketch

// GPIO Pins
const uint8_t LED_OUTPUT_PIN = LED_BUILTIN;
const uint8_t DOOR_OUTPUT_OPEN_PIN = 3;
const uint8_t DOOR_OUTPUT_CLOSE_PIN = 3;
const uint8_t LIGHT_OUTPUT_PIN = 2;
const uint8_t LIGHT_INPUT_PIN = 1;
const uint8_t SENSOR_OPEN_INPUT_PIN = 5;
const uint8_t SENSOR_CLOSED_INPUT_PIN = 4;

**Comment by washcroft** [comment]
Hello,
The pins in the example config won't work on the ESP8266, as they're what I used on a MKR1000. That's why it's currently crashing, before it's even started during pin setup.

I have just tested this with Wemos D1 mini, and here are some example pins that work for that board:

```
// GPIO Pins
const uint8_t LED_OUTPUT_PIN = LED_BUILTIN;
const uint8_t DOOR_OUTPUT_OPEN_PIN = D1;     // D1 = GPIO5
const uint8_t DOOR_OUTPUT_CLOSE_PIN = D1;    // D1 = GPIO5
const uint8_t LIGHT_OUTPUT_PIN = D2;         // D2 = GPIO4
const uint8_t LIGHT_INPUT_PIN = D5;          // D5 = GPIO14
const uint8_t SENSOR_OPEN_INPUT_PIN = D6;    // D6 = GPIO12
const uint8_t SENSOR_CLOSED_INPUT_PIN = D7;  // D7 = GPIO13
```

Best Regards,
Warren
