### ISSUE TITLE
Auto closing

### ISSUE THREAD

**Issue by davidkinders** [washcroft/HttpGarageDoorController#5]
Hello,

I have a problem: When the door is open (sensor triggerd) the door automatically is closing around 42 seconds. Can't find the problem. 

Kind regards
David

**Comment by washcroft** [comment]
Hello David,
Do you have DOOR_AUTO_CLOSE_TIME set in your config? It should be 0 if you don't want to use that feature.

**Comment by davidkinders** [comment]
The time was set to 5min (30000), so i did't think this was the problem. But that seems cause the problem, thanks. 

BTW great code!

Kind regards
David

**Comment by washcroft** [comment]
I wonder if your sensors aren't being read properly? The door should only close after DOOR_AUTO_CLOSE_TIME has elapsed  since the door state last become "open" (open sensor active, closed sensor inactive).
